### ISSUE TITLE
[MB1] Mystery Booster

### ISSUE THREAD

**Issue by henstercoza** [andrewgioia/keyrune#130] opened 2020-08-11 07:55 UTC
Hi guys thank you for all your hard work .. really appreciate it 

Are you planning to make a Mystery Booster symbol?

**Comment by kodabb** [comment] 2020-08-11 21:19
mystery booster doesn't have a real set symbol, but i do hope they add something like a question mark (like on MKM) for it

**Comment by kodabb** [comment] 2020-08-11 21:21
possible dupe of #118

**Comment by henstercoza** [comment] 2020-08-17 08:40
I see most of the websites are using this symbol 
may we have one like this added under Unofficial Symbols, also a cool looking one for general usage 

https://postimg.cc/LYSX649m

**Comment by kodabb** [comment] 2020-08-17 12:13
ah good catch, that's the same that scryfall uses. I think it could work for MB, but not for general use

**Comment by andrewgioia** [comment] 2020-08-28 13:36
Yeah I guess the set itself doesn't have an official set symbol but it is nice to have something to refer to each set. I like what Scyfall did with the planeswalker symbol the cards use and can go with that.

**Comment by andrewgioia** [comment] 2020-08-28 14:09
Added in 3.6.7!

**Closed by andrewgioia** 2020-08-28 14:09 UTC
Labels: new-icon
