### ISSUE TITLE
Can't use the files from CDN

### ISSUE THREAD

**Issue by stash86** [andrewgioia/Keyrune#43] opened 2017-06-03 23:50 UTC
If I add the script using the CDN, I will get this error

> downloadable font: download failed (font-family: "Keyrune" style:normal weight:normal stretch:normal src index:1): content blocked source: http://cdn.jsdelivr.net/keyrune/latest/fonts/keyrune.woff2?v=3.0.1

hence no set symbol will be shown

**Comment by jimaek** [comment] 2017-06-04 07:30
Your browser blocked the file. Trying using HTTPS to load the file

**Comment by andrewgioia** [comment] 2017-06-05 14:57
I'm not seeing any error loading those assets either, it should be otherwise fine. If you have more information on how you're loading Keyrune or what your app is built on I could help a bit more.

**Comment by stash86** [comment] 2017-06-08 11:41
I'm working on a website. Loading it on the usual place (head of html).

So if I'm hosting the file locally on my server, and do this

> <link href="//www.helhalmshop.tk/css/keyrune-3.0.2.min.css" rel="stylesheet" type="text/css" />

the font loaded normally. But once I use the cdn link, I get that error.

And yes I use https, my whole website is forced to use https.

I tried to change the htaccess
`<IfModule mod_headers.c>
	<FilesMatch ".(eot|ttf|otf|woff|woff2)$">
	    Header set Access-Control-Allow-Origin "*"  
    	# Header set Access-Control-Allow-Credentials true
	</FilesMatch>
</IfModule>`
but to no success either

**Comment by andrewgioia** [comment] 2018-01-08 15:28
@stash86 Have you been able to get this working from the CDN? Your update says you're loading the files locally and most likely the issue is with permissions or your local file structure. This issue is about the CDN (which is working correctly) so I'm going to close it out, but if you have any issues or bugs to report please feel free to open a new issue.

**Closed by andrewgioia** 2018-01-08 15:28 UTC
Labels: cdn, needs info
