### ISSUE TITLE
Trouble with the HOU symbol

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#39] opened 2017-04-20 21:12 UTC
I am currently not quite sure how to import the css properly into the wiki, so I usually update the common css: https://mtg.gamepedia.com/MediaWiki:Common.css

From my point of view that looks correct. However when I try to display the HOU symbol it simply does not work: https://mtg.gamepedia.com/User:Yanderesliver/sandbox2 (at least in my browser I only see white rectangles)

I cleared the cache multiple times already... Any idea what might cause the issue? 
Did something went wrong with the update?

**Comment by andrewgioia** [comment] 2017-04-21 14:41
That's really odd, I just tested it using the `latest` url and reproduced your problem. HOU isn't showing up for some reason, I don't know if it's a caching issue or an issue with `latest` pointing to the correct font files.

When I used the full `2.3.0` url then HOU does show up (as in, //cdn.jsdelivr.net/keyrune/2.3.0/fonts/keyrune.eot). If you look at the [SVG file in the CDN repository](https://raw.githubusercontent.com/jsdelivr/jsdelivr/master/files/keyrune/2.3.0/fonts/keyrune.svg) it also confirms that HOU is in that version, which also leads me to believe that `latest` doesn't update it's cache quickly enough. 

For now, if possible, I'd recommend using the version number in the CDN url. I'll continue to monitor it to see if there's something we can do to make sure it refreshes faster.

**Comment by yandere-sliver** [comment] 2017-04-21 16:29
Thanks that is a nice work around.
Since I have to update the css manually due to the weird wiki css thing, it is in essence not more work.

I am not even sure what the issue is because if you follow: http://cdn.jsdelivr.net/keyrune/latest/fonts/keyrune.svg
and look at the source code you see that the hou symbol is thate.

**Comment by andrewgioia** [comment] 2017-04-24 12:21
Yeah that would lead me to believe it's not a caching issue so I'm really at a loss here. I tested `/latest` again this morning and HOU is now working using it; I'll test for a delay in the next new icon update and see if it happens again.

**Comment by andrewgioia** [comment] 2017-07-09 17:32
@yandere-sliver has the `/latest` url been working for you and your projects? I think that's been resolved since jsDelivr's switch in how they handle npm projects and if so I can close this one out.

**Closed** 2017-07-15 14:35 UTC
Labels: bug, cdn, in review
